### PR TITLE
Add ability to create fresh VM rather than clone

### PR DESCRIPTION
**Pull request by jonrober**
For our local installs there are a lot of variances, so we usually create
VMs fresh rather than cloning.  I've added a create command that mostly uses
the same requirements as clone, but with a disk size and optional folder
setting.

### CODE REVIEW

**Comment by snobear** [comment]
@jonrober thanks for the PR!  However, there is a lot of duplicated code between `clone` and `create`.  We would want to move that common code out to one or more helper functions.  Let me know if you can work on that.

**Comment by jonrober** [comment]
Yeah, good point.  That worked for hacking at it but isn't great for actual release.  I'll work on cleaning that up.

**Comment by snobear** [comment]
@jonrober awesome, this will be very useful.

**Comment by snobear** [comment]
Also, be sure to rebase your branch with origin/master first as I just pushed some minor changes.

**Comment by jonrober** [comment]
Okay, here's a first pass at least at splitting things up.  One side-effect is that the --folder option will also work for clone now.

**Pull request closed without merging**
